Algoritmo "CONCIONAL SIMPLES"

Var
   ANO, NASC, IDADE : Inteiro

Inicio
      Escreva ("Em que ano estamos:")
      Leia (ANO)
      Escreva ("Em que ano você nasceu:")
      Leia (NASC)
     IDADE<- ANO-NASC
     Escreva ("Em ", ANO, " você terá:", IDADE, " anos")
     Se (IDADE >=21) entao
          EscrevaL(" E já atingiu a maioridade")
         Senao (IDADE <=21 ) entao
        EscrevaL (" Você ainda não atingiu a maioridade")
     FimSe
     


Fimalgoritmo